### ISSUE TITLE
大佬 请问什么时候会继续更新这个系列？

### ISSUE THREAD

**Issue by sanbuphy** [Aurelius84/CUDATutorial#1]
如题

**Comment by Aurelius84** [comment]
感谢关注，最近项目比较忙，repo里的一些学习分享给delay了，会加紧更新的

**Comment by sanbuphy** [comment]
> 感谢关注，最近项目比较忙，repo里的一些学习分享给delay了，会加紧更新的

感谢，已经watch  期待更新
